apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestor-de-datos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestor-de-datos
  template:
    metadata:
      labels:
        app: gestor-de-datos
    spec:
      containers:
      - name: gestor-de-datos
        image: demopython:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: gestor-de-datos-service
spec:
  selector:
    app: gestor-de-datos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
